package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("c05-ElenaBalalaykina-lesson12")
    void generatedTest() {
        step("Open https://the-internet.herokuapp.com/", () -> {
            // todo
        });

        step("Go to 'Form Authentication'", () -> {
            // todo
        });

        step("Check log-in", () -> {
            // todo
        });

        step("Check log-out", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because your test steps contain text 'http...' and the page has &lt;title&gt;")
    @DisplayName("Page title test")
    void titleTest() {
        step("Open url 'https://the-internet.herokuapp.com/'", () ->
            open("https://the-internet.herokuapp.com/"));

        step("Checking that the page title has is 'The Internet'", () -> {
            String expectedTitle = "The Internet";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
}