package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Selectors.byLinkText;
import static com.codeborne.selenide.Selectors.byText;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;

public class AppTests extends TestBase {

    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("c05-ElenaBalalaykina-lesson12")
    void generatedTest() {

        step(String.format("Open url '%s/'", baseUrl), () ->
                open("/"));

        step("Go to 'Form Authentication'", () ->
                $(byLinkText("Form Authentication")).click());

        step("Check log-in", () -> {
            $("#username").setValue(username);
            $("#password").setValue(password);
            $("[type=submit]").click();

            $(".flash.success").shouldHave(text("You logged into a secure area!"));
        });

        step("Check log-out", () -> {
            $("a.button").$(byText("Logout")).click();

            $(".flash.success").shouldHave(text("You logged out of the secure area!"));
        });
    }

    @Test
    @Description("Autogenerated, because your test steps contain text 'http...' and the page has &lt;title&gt;")
    @DisplayName("Page title test")
    void titleTest() {
        step(String.format("Open url '%s/'", baseUrl), () ->
                open("/"));

        step("Checking that the page title has is 'The Internet'", () -> {
            String expectedTitle = "The Internet";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
}